name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack # 새로 추가된 단계
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Type check
        run: yarn type-check # tsconfig에 따라

      - name: Build
        run: yarn build

      # 테스트가 있다면
      - name: Test
        run: yarn test --passWithNoTests
